### ISSUE TITLE
Error when running the PV module in JModelica.org

### ISSUE THREAD

**Issue by Ja98** [UdK-VPT/BuildingSystems#112] opened 2018-03-08 10:57 UTC
Are your models compatible with JModelica? I run into the following error when running the example PV module file: 

Error at line 14, column 9, in file 'H:\Modelica\Modelica Libraries\BuildingSystems-master\BuildingSystems\Utilities\NetCDF_DataReader\NcDataReader.mo':
  Cannot find function declaration for nc.ncEasyGetAttributeDouble()

Error at line 19, column 10, in file 'H:\Modelica\Modelica Libraries\BuildingSystems-master\BuildingSystems\Utilities\NetCDF_DataReader\NcDataReader.mo':
  Cannot find function declaration for nc.ncEasyGet1D()

**Comment by thorade** [comment] 2018-03-08 12:11
We have developed and tested our models only with Dymola + Visual Studio, so I am not sure what works with JModelica. Parts of our library should defininetely work, everything that is copied from the IBPSA library has also been tested with JModelica.

The error you are getting is from the weather data reader, we are using this library:
https://github.com/tbeu/netCDF-DataReader
Could you try and test whether that library (it contains some examples) works with JModelica?

**Comment by Ja98** [comment] 2018-03-08 14:07
Thanks for your reply. I have an evaluation version of Dymola and there is a problem with netCDF-Data Reader even in Dymola when checking the example file (see the attached image). The issue seems to be with the structure of the package? Are you able to simply download the .zip file from the repository and then simulate the components? 

![netcdf error](https://user-images.githubusercontent.com/36200412/37152895-2250a898-22db-11e8-9b02-3d584b825426.png)

**Comment by thorade** [comment] 2018-03-08 17:45
The netCDF library is a separate library, and it does not get opened automatically. So hopefully, the fix for your problem is simple: first open the netCDF library in Dymola, and then the BuildingSystems library, so that you have both libraries open simultaneously.

**Comment by thorade** [comment] 2018-03-08 17:46
Note: Crosslink to the issue in the netCDF issue tracker:
https://github.com/tbeu/netCDF-DataReader/issues/12

**Comment by Ja98** [comment] 2018-03-09 11:09
Thanks for your assistance with this error. Your fix worked for the locating the library - for JModelica I copied the netCDF package into the MSL directory of the installation. The preliminary checks in Dymola are now working; however I am still having the issue when the code is run in JModelica:

> CcodeCompilationError: Compilation of generated C code failed.

This error occurs both in the BuildingSystems library and the netCDF examples. I am new to Modelica and would not know where to start in debugging the compiler. I am beginning to get the impression that most libraries, particularly in the Buildings industry, are developed in Dymola and therefore without considerable compatibility work, it is not possible to run them in other software environments such as OpenModelica or JModelica.

**Comment by thorade** [comment] 2018-03-09 21:00
That impression is not wrong. In the past, many libraries have been developed with Dymola, but more recently, there is progress on both sides to improve compatibility. 

There are at least four libraries that reuse the IBPSA core library: AixLib, Buildings, BuildingSystems, IDEAS. The IBPSA library is compatible with JModelica, so that part of AixLib and BuildingSystems should work. The Buildings library should be fully compatible with JModelica, IDEAS has a branch for investigating JModlica compatibility, too. 

The BuildingSystem library is also getting test by OpenModelica:
https://libraries.openmodelica.org/branches/master/BuildingSystems/BuildingSystems.html

**Comment by thorade** [comment] 2018-03-12 08:38
This seems to be a duplicate of https://github.com/UdK-VPT/BuildingSystems/issues/104#issuecomment-357171732
The problem is that the netCDF library uses some DLLs (on Windows) or SO files (on Linux), and these need to be compiled with the same compiler that you are using when compiling the Modelica model. Not sure how exact the match has to be (version, bitness, OS, any thing else?).
JModelica on Windows seems to be using GCC. GCC is also used by OpenModelica, and it can be used in Dymola. The combination Dymola+GCC also fails.

The fix would be to either compile the dlls yourself, or ask to have the dlls you need for your specific setup included. 
The second option has already been asked for:
https://github.com/tbeu/netCDF-DataReader/issues/6
https://github.com/tbeu/netCDF-DataReader/issues/11
https://github.com/tbeu/netCDF-DataReader/issues/12 (your issue)
It might not be immediately obvious, but these three would be solved by the same fix: adding gcc compile dlls.

**Comment by thorade** [comment] 2018-03-12 10:54
@Ja98 Could you please post what GCC version you are using? And do you use 32 or 64 bit (Note: I strongly recommend 64bit!)

**Comment by Ja98** [comment] 2018-03-12 11:12
@thorade  Thanks for your assistance with this problem. I'm not sure how to check the GCC version but within the JModelica.org-2.1 installation file is a folder named gcc-4.7.2. Does this help? In terms of 64 or 32 bit, I downloaded the .exe file from [the JModelica website](http://www.jmodelica.org/binary ), I'm not sure if it's 32 or 64bit

**Comment by thorade** [comment] 2018-03-12 12:13
It seems JModelica is always 32 bit!? Not sure. I have here the dll, compiled with GCC 4.7.2 32bits on Windows. Could you please try and extract the files and copy them to either `NcDataReader2\Resources\Library\win32` or `NcDataReader2\Resources\Library\win32\gcc472`.
If that works, I will also send them as PR to the netCDF library.
[gcc472.zip](https://github.com/UdK-VPT/BuildingSystems/files/1802656/gcc472.zip)

**Comment by Ja98** [comment] 2018-03-12 13:14
@thorade thanks for that, I extracted the files over as you suggested. But I am now receiving the error 
> FMUException: Could not load the DLL: The specified module could not be found. (see the full error below ). 

Not sure if it's useful, but I've copied both the BuildingSystems and the NcDataReader2 package into the JModelica standard library folder. This means that both packages are loaded automatically. I am now calling the simulation with: 
 `pv = compile_fmu('BuildingSystems.Technologies.Photovoltaics.Examples.PVModuleSimple')`


```

> FMUException                              Traceback (most recent call last)
> <ipython-input-5-db8951d86bc9> in <module>()
>       1 pv = compile_fmu('BuildingSystems.Technologies.Photovoltaics.Examples.PVModuleSimple')
> ----> 2 model = load_fmu(pv)
> 
> > src\pyfmi\fmi.pyx in pyfmi.fmi.load_fmu (src\pyfmi\fmi.c:78588)()
> > 
> > src\pyfmi\fmi.pyx in pyfmi.fmi.FMUModelME1.__init__ (src\pyfmi\fmi.c:31615)()
> > 
> > src\pyfmi\fmi.pyx in pyfmi.fmi.FMUModelBase.__init__ (src\pyfmi\fmi.c:13311)()
> > 
> > FMUException: Could not load the DLL: The specified module could not be found.
```

**Comment by tbeu** [comment] 2018-03-12 13:20
So compilation seems no longer to fail.

Can you please check the FMU in the FMU compliance checker.

**Comment by Ja98** [comment] 2018-03-12 16:03
@tbeu sorry for my lack of knowledge but I am struggling to install and use the compliance checker. I have downloaded the files from `[here]([https://github.com/modelica-tools/FMUComplianceChecker])` but after trying to follow the instructions on GH I am not sure how to use the program. I have tried to build using cmake-gui but I am not sure of the arguments I need to enter. 

![cmake fmu compliance](https://user-images.githubusercontent.com/36200412/37293928-fa6cb398-2614-11e8-9f81-46ad37cc16f7.png)

**Comment by tbeu** [comment] 2018-03-12 16:22
You can use the pre-built binaries: https://trac.fmi-standard.org/browser/branches/public/Test_FMUs/Compliance-Checker/FMUChecker-2.0.4-win32.zip

OK, might be easier for you to add the FMU here.

**Comment by Ja98** [comment] 2018-03-12 16:42
@tbeu sorry when I first visited that page the download wasn't working for me so I just assumed it was a log. Ok so I've run the compliance checker. The checker outputs the following fatal errors:

```
[FATAL][FMICAPI] Could not load the DLL: The specified module could not be found.

[FATAL][FMUCHK] Could not create the DLL loading mechanism(C-API).
```
If it helps I've also attached the problem FMU:

[FMU.zip](https://github.com/UdK-VPT/BuildingSystems/files/1803698/FMU.zip)

**Comment by tbeu** [comment] 2018-03-12 18:09
OK, that was as expected. The FMU only contains binaries of
* BuildingSystems_Technologies_Photovoltaics_Examples_PVModuleSimple.dll
* netcdf.dll

If you remove the wrong netcdf.dll and instead add
* netcdf.dll from NcDataReader2\Resources\Library\win32\gcc472
* libcurl.dll from NcDataReader2\Resources\Library\win32\gcc472
* libgcc_s_dw2-1.dll from JModelica.org-2.1\MinGW\bin\libgcc_s_dw2-1.dll
* libz-1.dll from JModelica.org-2.1\MinGW\bin\libgcc_s_dw2-1.dll

the FMU is self-contained (w.r.t. the run-time libraries) and runs in the FMU Compliance Checker (though it complains about the missing data file).

**Comment by Ja98** [comment] 2018-03-13 08:30
@tbeu I'm sorry, where do I need to add these binaries? 

The content of the `C:\JModelica.org-2.1\install\ThirdParty\MSL\NcDataReader2\Resources\Library\win32` is currently:

hdf5.dll
hdf5_hl.dll
ITI_ncDataReader2.dll
libcurl.dll
libncDataReader2.a
libnetcdf.a
libnetcdf.dll
ncDataReader2.lib
netcdf.dll
netcdf.lib
zlib1.dll

Also there is no libgcc_s_dw2-1.dll or libz-1.dll  in my JModelica.org-2.1\MinGW\bin

**Comment by thorade** [comment] 2018-03-13 08:32
@Ja98 I have filed a Pull Request that should add the files in the correct place. Once that gets accepted and merged, you should download a new zip of netCDF (or better: learn [git](https://git-scm.com/downloads/guis)) and try again.
Having all files in the correct place still is not a guarantee that the simulation will wok in JModelica though!

**Comment by tbeu** [comment] 2018-03-13 08:48
Here [it](https://github.com/UdK-VPT/BuildingSystems/files/1806114/FMU.zip) comes.

**Comment by Ja98** [comment] 2018-03-13 11:58
@thorade @tbeu looks like both of those solutions worked! Thanks for assisting with this. Although going forward I am still unsure of what you did to rectify this :| was the only difference the absence of .dll files? Is this something that can be rolled out to address compatibility issues across other libraries/packages? If so is there any resource that provides information on how to compile the necessary .dll files?

**Comment by thorade** [comment] 2018-03-13 12:09
Pure Modelica code should in theory run in all [tools](https://modelica.org/tools), like Dymola, SimulationX, OpenModelica, JModelica. If it does not, it could be a limitation of the tool, or a case where the specification is not clear enough, or just low quality code. This can be addressed by automated cross-tool testing, something only very few libraries do...

What happened here was something different: Modelica can interact with existing code, by interfacing either the (C or Fortran) code directly, or by interfacing a binary file (dll, lib, so). The netCDF library is using external binaries. These binaries have to be compiled with the same compiler setup, which is easy for one tool+compiler, but gets difficult for all existing tool+compiler combinations.

**Comment by thorade** [comment] 2018-03-13 12:15
Closing this issue, as it seems to be fixed for you!?
You can still comment or reopen.

I guess you will very soon find other models that do not run in JModelica, please open new tickets for these.

**Closed by thorade** 2018-03-13 12:15 UTC

**Comment by Ja98** [comment] 2018-03-13 12:56
@thorade thanks very much for your comprehensive answer.
